{
 "title": "IPerf 3 Data Grabber version 0.16",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "test_id",
    "label": "Test ID",
    "query": "select test_id from iperf3_general_info order by test_time desc limit 1;"
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": "select protocol from iperf3_start_test_start order by test_id desc limit 1;"
   },
   {
    "name": "socket",
    "label": "Sockets",
    "query": "select distinct(socket) from iperf3_intervals_streams where test_id=(select test_id from iperf3_general_info order by test_id desc limit 1);"
   },
   {
    "name": "num_streams",
    "label": "# of streams",
    "query": "select num_streams from iperf3_start_test_start order by test_id desc limit 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Test overview",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  test_id,protocol,num_streams,duration,reverse\nFROM iperf3_start_test_start\norder by test_id desc limit 1;\n"
    }
   ]
  },
  {
   "title": "General Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  test_time,test_name, test_user, iperf3_client, iperf3_server,test_runs, args, test_complete\nFROM iperf3_general_info\norder by test_id desc limit 1;\n"
    }
   ]
  },
  {
   "title": "$protocol IPERF BITS PER SECOND - TOTALS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  bigint(bits_per_second) as value,\n  \nFROM iperf3_intervals_stream\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "select bits_per_second from iperf3_end_sum\n\nWHERE type=\"sum_sent\" and test_id=(select test_id from iperf3_general_info order by test_id desc limit 1)\n"
    },
    {
     "rawSql": "select bits_per_second from iperf3_end_sum\n\nWHERE type=\"sum_sent\" and test_id=(select test_id from iperf3_general_info order by test_id desc limit 1)\n"
    },
    {
     "rawSql": "select bits_per_second from iperf3_end_sum\n\nWHERE type=\"sum_sent\" and test_id=(select test_id from iperf3_general_info order by test_id desc limit 1)\n"
    }
   ]
  },
  {
   "title": "$protocol IPERF BITS PER SECOND - $num_streams SOCKETS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "PING STATISTICS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "CPU UTILIZATION",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "$protocol IPERF STATISTICS - SOCKET $socket",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "repeat": "socket",
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "$protocol IPERF STATISTICS - SOCKET $socket",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "$protocol IPERF STATISTICS - SOCKET $socket",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  }
 ]
}